[package]
name = "convo"
version = "0.1.0"
authors = ["Spencer Imbleau <spencer@imbleau.com>", "Thomas Houtart <thomas.houtart98@gmail.com>"]
edition = "2018"

[dependencies.convo-lib]
version = "*"
path = "convo-lib"

[workspace]
members = ["convo-lib"]