[package]
name = "convo"
version = "0.1.0"
authors = ["Spencer Imbleau <spencer@imbleau.com>"]
edition = "2018"

[dependencies.nom]
version = "6"
features = ["regexp"]

[dependencies.convo-lib]
version = "*"
path = "convo-lib"

[workspace]
members = ["convo-lib"]