name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
          - beta
    steps:
      - uses: actions/checkout@v3
      - name: Installing toolchain
        run: rustup update ${{ matrix.toolchain }}
      - name: Configuring toolchain
        run: rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
